name: code-coverage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install sfdx-cli
    - name: Populate auth file
      run: 'echo "${{ secrets.SALESFORCE_AUTH_URL }}" > ./SALESFORCE_AUTH_URL.txt'
    - name: Authenticate Dev Hub
      run: 'node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f ./SALESFORCE_AUTH_URL.txt -a devhub -d'
    - name: 'Create Scratch Org'
      run: sfdx org:create:scratch -f config/project-scratch-def.json -a ciorg -s -d 1 -v MyOrg
      shell: pwsh
    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:push
    - name: Run Apex tests
      run: node_modules/sfdx-cli/bin/run force:apex:test:run --codecoverage --resultformat human -d ./
    - name: Upload code coverage for Apex to Codecov.io
      uses: codecov/codecov-action@v2
      with:
        flags: Apex
    - name: Delete Scratch Org
      run: node_modules/sfdx-cli/bin/run force:org:delete --noprompt